### ISSUE TITLE
Lỗi tách email/địa chỉ web

### ISSUE THREAD

**Issue by kida7** [trungtv/pyvi#4]
Code hiện tại sẽ bị lỗi khi trong câu có email, địa chỉ web do sai regex. Ví dụ câu: 

> from pyvi import ViTokenizer, ViPosTagger
> x = ViTokenizer.tokenize('việt đẹp mã.ftp://mp3.zing.vn vinh@zing.com.vn')
> x

Mình đề xuất sửa regex của email, web trong method sylabelize thành 

> email = "[A-Za-z0-9-_\.]+@([A-Za-z0-9_-]+\.)+[A-Za-z0-9_-]+"
> web = "\w+://[^\s]+"

**Comment by trungtv** [comment]
@kida7 Cảm ơn bạn, thời gian qua mình hơi bỏ bê pyvi quá. Mình đã fix trong 0.0.9.3 rồi nhé
