### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by thanhtx1178793** [trungtv/pyvi#5]
Anh có thể cho em xin dataset được không ạ?

**Comment by trungtv** [comment]
Đợi chút nhé

**Comment by trungtv** [comment]
done

**Comment by dzpt** [comment]
@trungtv file vtb.txt này phải dữ liệu bạn train ko?
train ra chỉ tầm 4mb so với file có sẵn, 4.2mb.
và test kết quả ra cũng sai nhiều so với pyvipos3.pkl

**Comment by trungtv** [comment]
@dzpt đúng rồi mình train bằng vtb.txt.

**Comment by dzpt** [comment]
@trungtv tại mình có train lại, đúng với features có sẵn của bạn bằng vtb.txt.
thì size chỉ là 4mb và kết quả có sai khác so với việc dùng lại pyvipos3.pkl
nên nghĩ nếu bạn có update dataset (nếu có thay đổi) thì tốt quá.
