### ISSUE TITLE
pyvi tự động thêm khoảng trống trước sau các ký tự

### ISSUE THREAD

**Issue by TQuy** [trungtv/pyvi#6]
Lấy vị dụ một câu 

> "Nguyễn Thế Quý là sinh viên trường đại học Bách Khoa Hà Nội từ ngày 1/8/2014" 

thì pyvi sẽ segment thành 

> 'Nguyễn_Thế_Quý là sinh_viên trường đại_học Bách_Khoa Hà_Nội từ ngày 1 / 8 / 2014'

Và không có khả năng bắt đk 1/8/2014 là 1 token. Vấn đề này cũng được đề cập trong bài báo "A Feature-Rich Vietnamese Named-Entity Recognition Model" khi tokenize Mr.ABC thành Mr._ ABC. Mong admin có thể xem sét chỉnh sửa vì vấn đề này không hề nhỏ

**Comment by trungtv** [comment]
Chào em, 
Vấn đề em đưa ra là một lựa chọn tách hay ko tách nên mình cần thêm một vài feedback nữa để xem sao
